/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Load a sync session
 */
export const getSyncSessionPathSessionIdRegExp = new RegExp('^[a-zA-Z0-9_-]{6,64}$');


export const GetSyncSessionParams = zod.object({
  "sessionId": zod.coerce.string().regex(getSyncSessionPathSessionIdRegExp).describe('Public random sync code')
})

export const GetSyncSessionResponse = zod.object({
  "sessionId": zod.string(),
  "data": zod.object({
  "selectedCategoryKey": zod.string(),
  "currentCandidates": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "group": zod.string(),
  "avatar": zod.string()
})),
  "engineState": zod.record(zod.string(), zod.unknown()).nullable(),
  "sortedResults": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "group": zod.string(),
  "avatar": zod.string()
})),
  "currentView": zod.string(),
  "timestamp": zod.number().int()
}),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Save a sync session
 */
export const upsertSyncSessionPathSessionIdRegExp = new RegExp('^[a-zA-Z0-9_-]{6,64}$');


export const UpsertSyncSessionParams = zod.object({
  "sessionId": zod.coerce.string().regex(upsertSyncSessionPathSessionIdRegExp).describe('Public random sync code')
})

export const UpsertSyncSessionBody = zod.object({
  "data": zod.object({
  "selectedCategoryKey": zod.string(),
  "currentCandidates": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "group": zod.string(),
  "avatar": zod.string()
})),
  "engineState": zod.record(zod.string(), zod.unknown()).nullable(),
  "sortedResults": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "group": zod.string(),
  "avatar": zod.string()
})),
  "currentView": zod.string(),
  "timestamp": zod.number().int()
})
})

export const UpsertSyncSessionResponse = zod.object({
  "sessionId": zod.string(),
  "data": zod.object({
  "selectedCategoryKey": zod.string(),
  "currentCandidates": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "group": zod.string(),
  "avatar": zod.string()
})),
  "engineState": zod.record(zod.string(), zod.unknown()).nullable(),
  "sortedResults": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "group": zod.string(),
  "avatar": zod.string()
})),
  "currentView": zod.string(),
  "timestamp": zod.number().int()
}),
  "updatedAt": zod.coerce.date()
})


/**
 * Returns a presigned storage URL for direct image upload. The client
 * sends JSON metadata here, then uploads the file directly to storage.
 * @summary Request a presigned URL for file upload
 */





export const RequestUploadUrlBody = zod.object({
  "name": zod.string().min(1).describe('Original file name.'),
  "size": zod.number().int().min(1).describe('File size in bytes.'),
  "contentType": zod.string().min(1).describe('MIME type of the file.')
})






export const RequestUploadUrlResponse = zod.object({
  "uploadURL": zod.string().url().describe('Presigned storage URL for PUT upload.'),
  "objectPath": zod.string().describe('Normalized object path to store in sync data.'),
  "metadata": zod.object({
  "name": zod.string().min(1).describe('Original file name.'),
  "size": zod.number().int().min(1).describe('File size in bytes.'),
  "contentType": zod.string().min(1).describe('MIME type of the file.')
}).optional()
})


/**
 * Streams an image uploaded through the presigned URL flow.
 * @summary Serve an uploaded image
 */
export const GetStorageObjectParams = zod.object({
  "objectPath": zod.coerce.string().describe('Object path within the private object directory.')
})

export const GetStorageObjectResponse = zod.unknown()


