/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SyncCandidate {
  id: string;
  name: string;
  group: string;
  avatar: string;
  [key: string]: unknown;
 }

/**
 * @nullable
 */
export type SyncDataEngineState = { [key: string]: unknown } | null;

export interface SyncData {
  selectedCategoryKey: string;
  currentCandidates: SyncCandidate[];
  /** @nullable */
  engineState: SyncDataEngineState;
  sortedResults: SyncCandidate[];
  currentView: string;
  timestamp: number;
  [key: string]: unknown;
 }

export interface SyncSessionInput {
  data: SyncData;
}

export interface SyncSession {
  sessionId: string;
  data: SyncData;
  updatedAt: string;
}

export interface UploadUrlRequest {
  /**
     * Original file name.
     * @minLength 1
     */
  name: string;
  /**
     * File size in bytes.
     * @minimum 1
     */
  size: number;
  /**
     * MIME type of the file.
     * @minLength 1
     */
  contentType: string;
}

export interface UploadUrlResponse {
  /** Presigned storage URL for PUT upload. */
  uploadURL: string;
  /** Normalized object path to store in sync data. */
  objectPath: string;
  metadata?: UploadUrlRequest;
}

