/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Load a sync session
 */
export declare const getSyncSessionPathSessionIdRegExp: RegExp;
export declare const GetSyncSessionParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const GetSyncSessionResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    data: zod.ZodObject<{
        selectedCategoryKey: zod.ZodString;
        currentCandidates: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodString;
            name: zod.ZodString;
            group: zod.ZodString;
            avatar: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }>, "many">;
        engineState: zod.ZodNullable<zod.ZodRecord<zod.ZodString, zod.ZodUnknown>>;
        sortedResults: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodString;
            name: zod.ZodString;
            group: zod.ZodString;
            avatar: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }>, "many">;
        currentView: zod.ZodString;
        timestamp: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    }, {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    }>;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    data: {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    };
    updatedAt: Date;
}, {
    sessionId: string;
    data: {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    };
    updatedAt: Date;
}>;
/**
 * @summary Save a sync session
 */
export declare const upsertSyncSessionPathSessionIdRegExp: RegExp;
export declare const UpsertSyncSessionParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const UpsertSyncSessionBody: zod.ZodObject<{
    data: zod.ZodObject<{
        selectedCategoryKey: zod.ZodString;
        currentCandidates: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodString;
            name: zod.ZodString;
            group: zod.ZodString;
            avatar: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }>, "many">;
        engineState: zod.ZodNullable<zod.ZodRecord<zod.ZodString, zod.ZodUnknown>>;
        sortedResults: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodString;
            name: zod.ZodString;
            group: zod.ZodString;
            avatar: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }>, "many">;
        currentView: zod.ZodString;
        timestamp: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    }, {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    }>;
}, "strip", zod.ZodTypeAny, {
    data: {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    };
}, {
    data: {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    };
}>;
export declare const UpsertSyncSessionResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    data: zod.ZodObject<{
        selectedCategoryKey: zod.ZodString;
        currentCandidates: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodString;
            name: zod.ZodString;
            group: zod.ZodString;
            avatar: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }>, "many">;
        engineState: zod.ZodNullable<zod.ZodRecord<zod.ZodString, zod.ZodUnknown>>;
        sortedResults: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodString;
            name: zod.ZodString;
            group: zod.ZodString;
            avatar: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }, {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }>, "many">;
        currentView: zod.ZodString;
        timestamp: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    }, {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    }>;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    data: {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    };
    updatedAt: Date;
}, {
    sessionId: string;
    data: {
        selectedCategoryKey: string;
        currentCandidates: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        engineState: Record<string, unknown> | null;
        sortedResults: {
            id: string;
            name: string;
            group: string;
            avatar: string;
        }[];
        currentView: string;
        timestamp: number;
    };
    updatedAt: Date;
}>;
//# sourceMappingURL=api.d.ts.map