/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface SyncCandidate {
    id: string;
    name: string;
    group: string;
    avatar: string;
    [key: string]: unknown;
}
//# sourceMappingURL=syncCandidate.d.ts.map