/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { SyncCandidate } from './syncCandidate';
import type { SyncDataEngineState } from './syncDataEngineState';
export interface SyncData {
    selectedCategoryKey: string;
    currentCandidates: SyncCandidate[];
    /** @nullable */
    engineState: SyncDataEngineState;
    sortedResults: SyncCandidate[];
    currentView: string;
    timestamp: number;
    [key: string]: unknown;
}
//# sourceMappingURL=syncData.d.ts.map