/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { SyncData } from './syncData';
export interface SyncSession {
    sessionId: string;
    data: SyncData;
    updatedAt: Date;
}
//# sourceMappingURL=syncSession.d.ts.map