/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UploadUrlRequest } from './uploadUrlRequest';

export interface UploadUrlResponse {
  /** Presigned storage URL for PUT upload. */
  uploadURL: string;
  /** Normalized object path to store in sync data. */
  objectPath: string;
  metadata?: UploadUrlRequest;
}
